# The hour and minute when the server should restart (24 hour format)
restartTime:
- '00':00'
# Add multiple times by adding a new line like: - '12:00'

# Configure message and the corresponding pre-warning time in seconds
messages:
  '0': Restarting now
  '1': Restarting in 1 second
  '2': Restarting in 2 seconds
  '3': Restarting in 3 seconds
  '60': Restarting in 1 minute
  '120': Restarting in 2 minutes
  '180': Restarting in 3 minutes
  '300': Restarting in 5 minutes
